name: deploy-action-simple

on: [push] 

permissions:
  id-token: write
  contents: read
  pages: write

  
jobs:
  example_matrix:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14, 16]
        include:
          - os: windows-latest
            node: 16
            npm: 6
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Node  
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      
      - name: Install Dependencies    
        if: ${{ matrix.npm }}
        run: npm install -g npm@${{ matrix.npm }}
      - run: npm --version

      - name: Build Project
        run: npm run build/${{ matrix.os }}-${{ matrix.version }

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: github-pages-${{ matrix.os }}-${{ matrix.version }}
          path: build/${{ matrix.os }}-${{ matrix.version }/github-pages-${{ matrix.os }}-${{ matrix.version }}
      
